book_review/book/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    TextAreaField,
    SelectField,
    FileField,
    ValidationError,
    FloatField
)
from wtforms.validators import DataRequired, Length, Email, NumberRange
from flask_pagedown.fields import PageDownField
from book_review.models import Book

# tag choices for book
book_tags = [
    ("Null", "Choose..."),
    ("education", "Education"),
    ("development", "Development"),
    ("growth", "Personal Growth"),
    ("programming", "Programming"),
    ("novel", "Novel"),
    ("fiction", "Fiction"),
    ("spiritual", "Spiritual"),
]


class BookForm(FlaskForm):
    book_title = StringField(
        label="Title", validators=[DataRequired(), Length(max=120)]
    )
    author_name = StringField(
        label="Author", validators=[DataRequired(), Length(max=40)]
    )
    cover_image_file = FileField(label="Upload Cover Image")
    isbn = StringField(label="ISBN", validators=[DataRequired()])
    genre = SelectField(label="Genre", choices=book_tags)
    rating = FloatField(label="Rating", validators=[NumberRange(min=0, max=5)])
    shop_link = StringField(label="Shop Link")
    tiny_summary = TextAreaField(
        label="Tiny Summary",
        validators=[DataRequired()],
        render_kw={"placeholder": "few words ..."},
    )
    submit = SubmitField(label="Save")


class ReviewForm(FlaskForm):
    review_content = PageDownField(label="Write a review")
    publish = SubmitField(label="Publish")
    save_draft = SubmitField(label="Save Draft")


class CommentForm(FlaskForm):
    name = StringField(label="Name", default="Anonymous")
    email = StringField(label="Email", validators=[DataRequired(), Email()])
    comment_text = TextAreaField(label="Comment", render_kw={"rows": 4})
    submit = SubmitField(label="Comment")

book_review/admins/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from book_review import bcrypt, db
from book_review.models import Admin, Comment, Book
from book_review.admins.forms import LoginForm, AdminRegistrationForm


admins = Blueprint("admins", __name__)

# add admins
@admins.route("/admin/add", methods=["GET", "POST"])
@login_required
def add():
    form = AdminRegistrationForm()

    if form.validate_on_submit():
        admin_user = Admin(
            email=form.email.data,
            password=bcrypt.generate_password_hash(form.password.data).decode("utf-8"),
        )
        try:
            db.session.add(admin_user)
            db.session.commit()
            flash(
                f"Successfully registered new admin with: {form.email.data}", "success"
            )
            return redirect(url_for("admins.add"))
        except:
            flash("Some error occurred", "danger")

    return render_template("add_admin.html", form=form, title="Add new admin")


# login page
@admins.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in!", "success")
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        admin = Admin.query.filter_by(email=form.email.data).first()
        if admin and bcrypt.check_password_hash(admin.password, form.password.data):
            login_user(admin)
            flash("Login successful", "success")
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        flash("login unsucessful", "danger")
    return render_template("login.html", form=form, title="Login as Administrator")


# logout
@admins.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@admins.route("/comments")
@login_required
def comments():
    com = Comment.query.join(Book, Book.id == Comment.book_id)\
    .add_columns(
        Book.book_title, 
        Comment.id,
        Comment.comment_text, 
        Comment.date_added, 
        Comment.email, 
        Comment.name,
        Comment.verified)\
    .order_by(Comment.date_added.desc())\
    .all()
    return render_template("comments.html", comments=com)

@admins.route("/comment/approve/<comment_id>")
def approve_comment(comment_id):
    com = Comment.query.filter_by(id=comment_id).first()
    if not com:
        flash("Comment id not found", "info")
        redirect(url_for('admins.comments'))
    try:
        com.verified = True
        db.session.commit()
    except:
        flash("Some error occured in the database", "danger")
        return redirect(url_for("admins.comments"))
    flash("Comment was successfully approved", "success")
    return redirect(url_for("admins.comments"))
    
@admins.route("/comment/delete/<comment_id>")
def delete_comment(comment_id):
    com = Comment.query.filter_by(id=comment_id).first()
    if not com:
        flash("Comment id not found", "info")
        redirect(url_for("admins.comments"))
    try:
        db.session.delete(com)
        db.session.commit()
    except:
        flash("Some error occured in the database", "danger")
        return redirect(url_for("admins.comments"))
    flash("Comment was successfully removed", "success")
    return redirect(url_for("admins.comments"))

book_review/book/routes.py
from slugify import slugify
from markdown2 import Markdown
from flask import Blueprint, flash, render_template, redirect, url_for, abort, request
from flask_login import login_required
from book_review import db
from book_review.models import Book, Comment
from book_review.book.forms import BookForm, ReviewForm, CommentForm
from book_review.book.utils import save_cover_image, delete_cover_image
from book_review.utils.helper import analysize_comment

markdowner = Markdown()

book = Blueprint("book", __name__)

# book/comment page
@book.route("/book/<book_slug>", methods=["GET", "POST"])
def present(book_slug):
    book = Book.query.filter_by(title_slug=book_slug).first()
    comments = Comment.query.filter_by(book_id=book.id).order_by(Comment.date_added.desc()).all()
    form = CommentForm()
    if form.validate_on_submit():
        for comment in comments:
            if comment.email == form.email.data and comment.book_id == book.id:
                flash(f"Cannot post this comment as you've already posted once.", "info")
                return redirect(url_for("book.present", book_slug=book.title_slug))
        verification = True if analysize_comment(form.comment_text.data) > 0.0 else False
        comment = Comment(
            name=form.name.data,
            email=form.email.data,
            comment_text=form.comment_text.data,
            book_id=book.id,
            verified=verification
        )
        try:
            db.session.add(comment)
            db.session.commit()
            flash("Comment was posted successfully!", "success")
            return redirect(url_for("book.present", book_slug=book.title_slug))
        except:
            flash("something went wrong!", "danger")

    return render_template(
        "book.html",
        book=book,
        title=book.book_title,
        markdowner=markdowner,
        form=form,
        comments=comments,
    )


# add book
@book.route("/book/add", methods=["GET", "POST"])
@login_required
def add():
    form = BookForm()

    if form.validate_on_submit():

        saved_book = Book.query.filter_by(isbn = form.isbn.data).first()
        if saved_book:
            flash(f"{saved_book.book_title} already exist in database!", "danger")
        else:
            filename = save_cover_image(form.cover_image_file)
            book = Book(
                book_title=form.book_title.data,
                title_slug=slugify(form.book_title.data),
                author_name=form.author_name.data,
                cover_image_file=filename if filename else "default.jpeg",
                isbn=form.isbn.data,
                genre=form.genre.data,
                tiny_summary=form.tiny_summary.data,
                rating=form.rating.data,
                shop_link = form.shop_link.data
            )
            try:
                db.session.add(book)
                db.session.commit()
            except:
                flash("Something went wrong while adding book to the database.", "danger")
                return render_template("add_book.html", form=form)

            flash("Book successfully added to the database", "success")
            return redirect(url_for("main.home"))

    return render_template("add_book.html", form=form, title="Add Book")


# edit book page
@book.route("/book/<book_slug>/edit", methods=["GET", "POST"])
@login_required
def edit(book_slug):
    book = Book.query.filter_by(title_slug=book_slug).first()

    if not book:
        abort(403)

    form = BookForm()

    if form.validate_on_submit():
        book.book_title = form.book_title.data
        book.author_name = form.author_name.data
        book.isbn = form.isbn.data
        book.shop_link = form.shop_link.data
        book.rating = form.rating.data
        book.tiny_summary = form.tiny_summary.data
        book.genre = form.genre.data
        if form.cover_image_file.data:
            delete_cover_image(book.cover_image_file)
            book.cover_image_file = form.cover_image_file.data
        try:
            db.session.commit()
        except:
            flash("Something went wrong while adding book to the database.", "danger")
            return render_template(
                "add_book.html", title=f"Edit {book.book_title}", form=form
            )
        flash("The book was updated!", "success")
        return redirect(url_for("book.present", book_slug=book.title_slug))
    elif request.method == "GET":
        form.book_title.data = book.book_title
        form.author_name.data = book.author_name
        form.isbn.data = book.isbn
        form.tiny_summary.data = book.tiny_summary
        form.genre.data = book.genre
        form.shop_link.data = book.shop_link
        form.rating.data = book.rating

    return render_template(
        "add_book.html", title=f"Edit {book.book_title}", form=form, book=book
    )


# delete book
@book.route("/book/<book_slug>/delete", methods=["POST"])
@login_required
def delete(book_slug):
    book = Book.query.filter_by(title_slug=book_slug).first()
    comments = Comment.query.filter_by(book_id=book.id).all()
    if not book:
        abort(403)
    try:
        for comment in comments:
            db.session.delete(comment)
        db.session.delete(book)
        db.session.commit()
        if book.cover_image_file != "default.jpg":
            delete_cover_image(book.cover_image_file)
    except:
        flash(f"Something went wrong!", "danger")
        return redirect(url_for("book.edit", book_slug=book_slug))
    flash(f"Alright, {book.book_title} was successfully deleted", "success")
    return redirect(url_for("main.home"))


# review page
@book.route("/book/<book_slug>/write_review", methods=["GET", "POST"])
@login_required
def write_review(book_slug):
    form = ReviewForm()
    book = Book.query.filter_by(title_slug=book_slug).first()
    if form.validate_on_submit():
        if form.save_draft.data:
            try:
                book.review_content_draft = form.review_content.data
                db.session.commit()
                flash("Draft was saved successfully", "success")
            except:
                flash("Something went wrong", "danger")
        elif form.publish.data:
            if not form.review_content.data:
                flash("Cannot publish empty review!", "danger")
                return redirect(url_for("book.write_review", book_slug=book.title_slug))
            try:
                book.review_content = form.review_content.data
                book.review_content_draft = form.review_content.data
                db.session.commit()
                flash("Review was published.", "success")
            except:
                flash("Something went wrong", "danger")
            return redirect(url_for("book.present", book_slug=book.title_slug))
    elif request.method == "GET":
        form.review_content.data = book.review_content_draft
    return render_template("write_review.html", form=form, book=book, title="Write Review")


@book.route("/books/search")
def search():
    search_query = request.args.get("bname", type=str)
    if not search_query:
        abort(404)
    books = Book.query.filter(Book.book_title.contains(search_query)).all()
    return render_template("list_books.html", title=f"Search results for \"{search_query}\"", books=books)

# book filtered by genre
@book.route("/books/genre/<name>")
def genre(name):
    books = Book.query.filter_by(genre = name).all()
    return render_template("list_books.html", books=books, title=f"Books on {name}")

book_review/main/routes.py
import os
from flask import Blueprint, render_template, request, send_from_directory
from book_review import app
from book_review.models import Book

main = Blueprint("main", __name__)


# home page
@main.route("/", methods=["GET"])
def home():
    page = request.args.get("page", default=1, type=int)
    books = Book.query.paginate(page=page, per_page=8)
    return render_template("home.html", books=books, title="Home", curr_page=page)


# about page
@main.route("/about", methods=["GET"])
def about():
    return render_template("about.html", title="About")


# send image file
@main.route("/uploads/<filename>")
def send_image_file(filename):
    return send_from_directory(os.path.join(app.instance_path, "uploads"), filename)

book_review/templates/about.html
{% extends "layout.html" %}

{% block content %}
<h1>About page</h1>
{% endblock %}

book_review/templates/add_book.html
{% extends "layout.html" %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">{{ title }}</legend>
        <div class="form-row">
            <!-- book title -->
            <div class="form-group col-md-6">
                {{ form.book_title.label(class="form-control-label") }}
                {% if form.book_title.errors %}
                {{ form.book_title(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.book_title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.book_title(class="form-control") }}
                {% endif %}
            </div>

            <!-- author's name -->
            <div class="form-group col-md-6">
                {{ form.author_name.label(class="form-control-label") }}
                {% if form.author_name.errors %}
                {{ form.author_name(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.author_name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.author_name(class="form-control") }}
                {% endif %}
            </div>

            <!-- isbn number -->
            <div class="form-group col-md-6">
                {{ form.isbn.label(class="form-control-label") }}
                {% if form.isbn.errors %}
                {{ form.isbn(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.isbn.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.isbn(class="form-control") }}
                {% endif %}
            </div>

            <!-- tag select field -->
            <div class="form-group col-md-6">
                {{ form.genre.label(class="form-control-label") }}
                {{ form.genre(class="form-control") }}
            </div>

            <!-- rating -->
            <div class="form-group col-md-6">
                {{ form.shop_link.label(class="form-control-label") }}
                {% if form.shop_link.errors %}
                {{ form.shop_link(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.shop_link.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.shop_link(class="form-control") }}
                {% endif %}
            </div>

            <!-- rating -->
            <div class="form-group col-md-6">
                {{ form.rating.label(class="form-control-label") }}
                {% if form.rating.errors %}
                {{ form.rating(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.rating.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.rating(class="form-control") }}
                {% endif %}
            </div>

            <!-- cover image file -->
            <div class="form-group">
                {{ form.cover_image_file.label(class="form-control-label") }}
                {% if form.cover_image_file.errors %}
                {{ form.cover_image_file(class="form-control-file is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.cover_image_file.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.cover_image_file(class="form-control-file") }}
                {% endif %}
            </div>
        </div>


        <!-- tiny summary -->
        <div class="form-group">
            {{ form.tiny_summary.label(class="form-control-label") }}
            {% if form.tiny_summary.errors %}
            {{ form.tiny_summary(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.tiny_summary.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.tiny_summary(class="form-control") }}
            {% endif %}
        </div>

        <!-- submit button -->
        <div class="form-group">
            {{ form.submit(class="btn btn-info") }}
            {% if book %}
            <a href="{{ url_for('book.present', book_slug=book.title_slug) }}" class="btn btn-outline-secondary">Cancel</a>
            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteBookConfirm">
                Delete Book
            </button>
            {% endif %}
        </div>
    </fieldset>
</form>
<!-- render only if book is passed -->
{% if book %}
<div class="modal fade" id="deleteBookConfirm" tabindex="-1" role="dialog" aria-labelledby="deleteBookConfirmModal"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm Deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete <strong>{{ book.book_title }}</strong>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{{ url_for('book.delete', book_slug=book.title_slug) }}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Delete" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

book_review/templates/book.html
{% extends "layout.html" %}

{% block content %}
<div class="row">
  <div class="col-md-4 col-lg-3 col-sm-5 col-8 mt-3">
    <img class="img-fluid" src="{{ url_for('main.send_image_file', filename=book.cover_image_file)}}"
      alt="{{ book.book_title }}">
  </div>
  <div class="col-md-8 col-lg-6 col-sm-7 mt-3">
    <h3 class="book-title">{{ book.book_title }}</h3>
    <p class="mt-1">by {{ book.author_name }}</p>
    <p class="mt-1">ISBN: 
      <a target="_blank" href="https://isbnsearch.org/isbn/{{ book.isbn }}">{{ book.isbn }}</a>
    </p>
    <p class="mt-1">Genre:
      <a href="{{ url_for('book.genre', name=book.genre) }}">{{ book.genre }}</a>
    </p>
    <p class="rating-stars">
      Rating: 
        {% for n in range(5) %}
        {% if n < book.rating//1 %}
        <span class="fa fa-star rating-star"></span>
        {% elif (book.rating - n) == 0.5 %}
        <i class="fas fa-star-half-alt rating-star"></i>
        {% else %}
        <span class="far fa-star rating-star"></span>
        {% endif %}
      {% endfor %}
      <span>{{ book.rating*1.0 }}</span>
    </p>
    <p class="mt-2">
      {{ book.tiny_summary }}
    </p>
    {% if current_user.is_authenticated %}
    <div class="btn-groups mt-2">
      <a href="{{ url_for('book.edit', book_slug=book.title_slug) }}" class="btn btn-sm btn-outline-info mr-2">Edit <i
          class="fas fa-edit"></i></a>
      <a href="{{ url_for('book.write_review', book_slug=book.title_slug) }}" class="btn btn-sm btn-primary">
        {% if book.review_content_draft %}
        Edit Review
        {% else %}
        Write Review
        {% endif %}
        <i class="fas fa-pen-square"></i>
      </a>
    </div>
    {% endif %}
  </div>
  {% if book.review_content %}
  <div class="col-12 mt-4">
    <h4><b>Review</b></h4>
    <div class="review-content">
      {{ markdowner.convert(book.review_content)|safe }}
    </div>
  </div>
  {% endif %}

  <div class="col-12 mt-4">
    {% if comments %}
    <h4 class="mb-2"><b>Comments</b></h4>
    {% for comment in comments %}
    {% if comment.verified %}
      <div class="comment-card mb-2">
        <div class="comment-date">
          <small>{{ comment.date_added.strftime('%d-%m-%Y %H:%M') }}</small>
        </div>
        <h5>{{ comment.name }} <i>says:</i></h5>
        <p>{{ comment.comment_text }}</p>
      </div>
    {% endif %}
    {% endfor %}
    {% endif %}
  </div>

  {% if not current_user.is_authenticated %}
  <div class="col-8 mt-4">
    <form action="" method="POST">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="mb-2">
          <h4><b>Add a comment</b></h4>
        </legend>
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form.name.label(class="form-control-label") }}
            {% if form.name.errors %}
            {{ form.name(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.name.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
            {{ form.name(class="form-control") }}
            <small class="form-text text-muted">Optional</small>
            {% endif %}
          </div>
          <div class="form-group col-md-6">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control") }}
            <small class="form-text text-muted">Email is required but will not be published.</small>
            {% endif %}
          </div>
          <div class="form-group col-md-12">
            {{ form.comment_text.label(class="form-control-label") }}
            {% if form.comment_text.errors %}
            {{ form.comment_text(class="form-control is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.comment_text.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %}
            {{ form.comment_text(class="form-control") }}
            {% endif %}
          </div>
        </div>
        <div class="form-group">
          {{ form.submit(class="btn btn-info") }}
        </div>
      </fieldset>
    </form>
  </div>
  {% endif %}
</div>
{% endblock %}

book_review/templates/comments.html
{% extends "layout.html" %}

{% block content %}
<table class="table">
    <thead>
        <tr>
            <th>Book</th>
            <th>Email</th>
            <th>Name</th>
            <th>Comment</th>
            <th>Date</th>
            <th>Unverified</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for comment in comments %}
        <tr>
            <td>{{ comment.book_title }}</td>
            <td>{{ comment.email }}</td>
            <td>{{ comment.name }}</td>
            <td>{{ comment.comment_text }}</td>
            <td>{{ comment.date_added.strftime("%d-%m-%Y %H:%M") }}</td>
            <td><a href="{{ url_for('admins.delete_comment', comment_id=comment.id) }}"class="btn btn-danger btn-sm">Delete</a></td>
            {% if comment.verified %}
                <td>Verified</td>
            {% else %}
                <td><a href="{{ url_for('admins.approve_comment', comment_id=comment.id) }}" role="button" class="btn btn-secondary btn-sm">Approve</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

book_review/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>
    {% if title %}
    {{ title }} |
    {% endif %}
    Book Reviews by Amrit Pandey
  </title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Work+Sans:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet"> 
</head>

<body>
  <div class="wrapper">
    <header class="main-header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand mr-2" href="{{ url_for('main.home') }}">
            Readaholic 
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if not current_user.is_authenticated %}
              <li class="nav-item">
                <a class="btn btn btn-outline-success" href="{{ url_for('admins.login') }}">Login</a>
              </li>
              {% else %}
              <li class="nav-item dropdown ml-3">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                  aria-haspopup="true" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{{ url_for('book.add') }}"><i class="fas fa-plus"></i> Add Book</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('admins.add') }}"><i class="fas fa-user-shield"></i> Create Admin</span></a></li>
                  <li><a class="dropdown-item" href="{{ url_for('admins.comments') }}"><i class="fas fa-comment"></i> Comments</span></a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{{ url_for('admins.logout') }}"><i class="fas fa-sign-out-alt"></i>Logout</span></a></li>
                </ul>
              </li>
              {% endif %}
            </ul>
            <form class="ml-auto d-flex" action="{{ url_for('book.search') }}" method="GET">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" name="bname">
              <button class="btn btn-info my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    <main class="main-section mt-4">
      <div class="container">
        <!-- flash messages -->
        {% with messages = get_flashed_messages(with_categories = True) %}
        {% if messages %}
        {% for cat, msg in messages %}
        <div class="alert alert-{{ cat }} alert-dismissible fade show" role="alert">
          {{ msg }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <!-- content block -->
        
        {% block content %} {% endblock %}
      </div>
    </main>
  </div>
  <footer class="main-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="site-links">
            <a href="">about</a>
            <a href="">privacy</a>
            <a href="">terms</a>
            <a href="">licenses</a>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="copyright-note">
            Copyrights &copy; 2019 Amrit Pandey
          </div>
        </div>
      </div>
    </div>
  </footer>
  <script src="{{ url_for('static', filename='js/jquery.slim.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
</body>

</html>